[project]
name = "streamlit-basics"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "pandas>=2.2.3",
    "streamlit>=1.44.0",
    "torch>=2.6.0",
]
